name: CI

on: push

jobs:
  test:
    name: Run kubeconform on Manifests
    runs-on: ubuntu-latest
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: "/kubeconform"
          args: "-summary -strict -output json manifests/"
